### ISSUE TITLE
Breaks Footnotes

### ISSUE THREAD

**Issue by SilentGlasses** [orbikm/mkdocs-ezlinks-plugin#56]
I use MkDocs with [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) and as soon as I enable ezlinks, it starts breaking my footnote links.

The instructions on adding footnotes say I only need to do this:

```
Here's a sentence with a footnote[^1].

[^1]: This is the footnote.
```

I have tried with the following and it still does not work:

```
plugins:
  - search
  - ezlinks:
      reference_links: true
      wikilinks: true
```
